name: Run Assignments

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-assignments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    # Assignment 1 Steps
    - name: Compile Java files (Assignment 1)
      run: |
        cd Assignment_1
        javac *.java
        rmic AdditionServiceImplementation

    - name: Start RMI Registry (Assignment 1)
      run: |
        cd Assignment_1
        nohup rmiregistry &

    - name: Start AdditionServer (Assignment 1)
      run: |
        cd Assignment_1
        nohup java AdditionServer &

    - name: Run Client and Check Result (Assignment 1)
      run: |
        cd Assignment_1
        java AdditionServiceClient 5 8
        echo "Expected output: 13"
        cd ..
      continue-on-error: false # Fail the workflow if the client process fails

    # Assignment 2 - String Reverse Steps
    - name: Generate IDL Files (Assignment 2 - String Reverse)
      run: |
        cd Assignment_2/StringReverse
        idlj -fall Reverse.idl
        javac *.java ReverseModule/*.java
        nohup orbd -ORBInitialPort 1057 & # Use a unique port for ORBD
        sleep 5
        nohup java Server -ORBInitialPort 1057 & # Start Server on the same port
        sleep 5

    - name: Run CORBA Client and Provide Input (Assignment 2 - String Reverse)
      run: |
        cd Assignment_2/StringReverse
        max_attempts=3
        attempt=1
        until [ $attempt -gt $max_attempts ]; do
          echo "Attempt $attempt to run ReverseClient..."
          echo "Hello World" | java ReverseClient -ORBInitialPort 1057 && break
          echo "ReverseClient failed on attempt $attempt. Retrying..."
          attempt=$((attempt + 1))
          sleep 1 # Wait before retrying
        done
        if [ $attempt -gt $max_attempts ]; then
          echo "ReverseClient failed after $max_attempts attempts."
          exit 1
        fi
        echo "Expected output: dlroW olleH"
        killall -9 orbd
      continue-on-error: true # Fail the workflow if the client process fails
      
    # Assignment 2 - Calculator Steps
    - name: Generate IDL Files (Assignment 2 - Calculator)
      run: |
        cd Assignment_2/Calculator
        idlj -fall Calculator.idl
        javac *.java CalculatorModule/*.java
        nohup orbd -ORBInitialPort 1056 &
        sleep 5
        nohup java Server -ORBInitialPort 1056 &
        sleep 5

    - name: Run CORBA Client and Provide Input (Assignment 2 - Calculator)
      run: |
        cd Assignment_2/Calculator
        echo "5 3" | java CalculatorClient -ORBInitialPort 1056
        echo "Expected output: 8 2 15 1.6666666"
      continue-on-error: false # Fail the workflow if the client process fails

    # Assignment 5 - Token Ring Steps
    - name: Compile TokenRing Program
      run: |
        cd Assignment_5
        javac TokenRing.java

    - name: Run TokenRing Program
      run: |
        cd Assignment_5
        echo -e "3\nHello\n1\n3\n0\n" | java TokenRing
        echo "Expected output: Simulates token ring message passing"
      continue-on-error: false # Fail the workflow if the client process fails
